version: '3.8'

services:
  app:
    build: .
    ports:
      - "6001:3000"
    depends_on:
      - db
      - db_test
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: topico_db
    networks:
      - app-network
    volumes:
      - .:/usr/app
    command: npm start

  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: topico_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  db_test:
    image: mysql:8.0
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: topico_db_test
    ports:
      - "3307:3306"
    volumes:
      - db_test_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:
  db_test_data:

networks:
  app-network:
    driver: bridge
